<?php

namespace Container5ApjU7U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailSenderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\EmailSender' shared autowired service.
     *
     * @return \App\Service\EmailSender
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service "App\\Service\\EmailSender": argument "$mailFromAddress" of method "__construct()" is type-hinted "string", you should configure its value explicitly.');
    }
}
