<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5ApjU7U\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5ApjU7U/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5ApjU7U.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5ApjU7U\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5ApjU7U\App_KernelDevDebugContainer([
    'container.build_hash' => '5ApjU7U',
    'container.build_id' => 'a2e54076',
    'container.build_time' => 1779034493,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container5ApjU7U');
